version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: b5a1453zxk
      MYSQL_DATABASE: db-gestion-app
      MYSQL_USER: user
      MYSQL_PASSWORD: b5a1453zxk
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
