name: Deploy of backend to EC2

on:
  push:
    paths:
      - gestion-app-nest-backend/**/*
    branches: [main]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  dependencies:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "gestion-app-nest-backend/*"
      - name: Installing dependencies
        run: cd gestion-app-nest-backend && npm install --production

  test:
    needs: [dependencies]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.0
        with:
          cache: "npm"
          node-version: "20"
          cache-dependency-path: "gestion-app-nest-backend/*"
      - name: Installing dependencies
        run: cd gestion-app-nest-backend && npm install --production
      - name: Testing
        run: cd gestion-app-nest-backend && npm run test

  build:
    needs: [dependencies]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "gestion-app-nest-backend/*"
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t aguekdjian/backend-gestion-app:latest gestion-app-nest-backend/.
      - name: Publish image to docker hub
        run: docker push aguekdjian/backend-gestion-app:latest

  deploy:
    needs: [test, build]
    runs-on: aws-ec2-gestion-app
    steps:
      - name: Login to docker hub
        run: sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Delete old docker image
        run: sudo docker image prune
      - name: Pull Image from docker hub
        run: sudo docker pull aguekdjian/backend-gestion-app:latest
      - name: Delete old container
        run: sudo docker rm -f backend-gestion-app-container
      - name: Run docker container
        run: sudo docker run -d -p 3000:3000 --name backend-gestion-app-container -e JWT_SECRET=${{secrets.JWT_SECRET}} aguekdjian/backend-gestion-app:latest
